-- Create one user for the location
-- Create one location
INSERT INTO backend_customer (id, email_address, password, salt, date_created, date_modified) VALUES (1, "anuj@soundit.ca", "02b31057a8571be94458daa3fe170719", "69", now(), now());
INSERT INTO backend_location (id, customer_id, name, location, phone_number, date_created, date_modified) VALUES (1, 1, "The Pit", "UBC, Vancouver", "(604) 441-2685", now(), now());

-- Create one playlist
INSERT INTO backend_playlist (id, location_id, date_created, date_modified) VALUES (1, 1, now(), now());


-- Create a bunch of categories.
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Hip Hop/Rap", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Dance", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Hip Hop/ RnB", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("RnB/Soul", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Pop", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Hip Hop/ Rap", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Rock", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Alternative", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("Electronic", now(), now(), 0);
INSERT INTO backend_musiccategory (name, date_created, date_modified, is_deleted) VALUES ("R&B/ Soul", now(), now(), 0);


-- Create a bunch of albums.
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Pink Friday", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Axwell Presents Axtone Vol.1", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Daytrotter Studio  10/11/2011", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Cross Road", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("ThisSongIsSick.com", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Sufferer & the Witness", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("All The Right Reasons", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Wild Ones", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Overexposed", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Up All Night", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("21", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("[Led Zeppelin IV]", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Nirvana", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("4", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Clique", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Is This It", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Believe", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Best of AC/DC", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("We Are Young", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Street King Immortal", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Unapologetic", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Greatest Hits", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Curiosity", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Matangi", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Konvict", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("One More Love", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Feel So Close", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Twilight Saga: Breaking Dawn", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Sublime", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Nothing but the Beat", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Heist", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Truth About Love", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Well Done 3", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Favourite Worst Nightmare", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Waking Up", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Angel Single", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Black Holes and Revelations", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Drive By", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Born This Way", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Red", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Eminem Show", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Unorthodox Jukebox", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("El Camino", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("willpower", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Weezer (Green Album)", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Twilight Sage: Breaking Dawn", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Torches", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Rated R", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Freedom", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("It's Time", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Enema of the State", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("This Love", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Take the Crown", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Oracular Spectacular", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("PSY 6", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Dookie", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Take Care", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Hybrid Theory", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Global Warming", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Talk That Talk", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Trilogy", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Lights", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Rack City- Single", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Appetite for Destruction", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Watch the Throne", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Immersion", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Uprising", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Dear Agony", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Lose Yourself", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Scar Tissue", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Pjanoo", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Better Life", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Foo Fighters", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Meteora", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Faded", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Just a Dream", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Live in Texas", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Curtain Call: The Hits", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Party Rock Anthem", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Backspacer", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Anthology", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Hurry Up, We\'e2\'80\'99re Dreaming", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Away From the Sun", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Hands All Over", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Police", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Sorry for Party Rocking", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Until Now", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Mylo Xyloto", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Man on the Moon: The End of Day", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Titanium", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Making Mirrors", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("No Leaf Clover", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Teenage Dream", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("DJ Got Us Falling In Love Again", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Endgame", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("My Head Is an Animal", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Call On Me", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("U2 18 Greatest Hits", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Appeal to Reason", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("GoodMusicAllDay.com Presents The Best Of June 5 - 10, 2011", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("(What's The Story) Morning Glory?", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Scary Monsters and Nice Sprites", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Reload", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Serious Things", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("City of Dreams", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Warrior", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Take Me Home", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Bon Jovi: Greatest Hits", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("18 Months", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The Ultimate Experience", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Girl on Fire", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("By the Way", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Songs About Jane", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("Doo-Wops & Hooligans", now(), now(), 0);
INSERT INTO backend_album (name, date_created, date_modified, is_deleted) VALUES ("The 20/20 Experience", now(), now(), 0);

-- Create a bunch of artists.
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Pink", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Foster The People", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Nicki Minaj", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Beyonce", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Rihanna", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Avicii", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("The Weeknd", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Alicia Keys", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("David Guetta & Sia", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Blink-182", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("50 cent", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Eminem", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Nirvana", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Green Day", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Psy", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Breaking Benjamin", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Carly Rae Jepsen", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Drake", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("The Black Keys", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Alesso & Dirty South", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("MGMT", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Sublime", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("The Strokes", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Pendulum", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Flo Rida", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Akon ft Eminem", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Macklemore", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Imagine Dragons", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Arctic Monkeys", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Ke$ha", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("David Guetta", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Katy Perry", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Red Hot Chili Peppers", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("U2", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Pearl Jam", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Tyga", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Bryan Adams", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("fun.", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Guns N' Roses", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Gym Class Heroes [Ft. Adam Levine]", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Muse", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Nelly", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Usher", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("OneRepublic", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Metallica", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Ellie Goulding", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Led Zeppelin", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Nickelback", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Swedish House Mafia", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("One direction", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Pitbull", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Weezer", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Christina Perri", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Oasis/oasis", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Queen", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Maroon 5", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Akon, Colby O'Donis & Kardinal Offishal", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Gotye", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Axwell, Ingrosso & Laidback Luke", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("M.I.A", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Justin Timberlake", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Armin Van Buuren", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("LMFAO", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Skrillex", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Akon", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Train", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Of Monsters and Men", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Foo Fighters", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Kid Cudi", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("AC/DC", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Kanye West", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("will.i.am", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Adele", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("3 Doors Down", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("The Police", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Coldplay", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Taylor Swift", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Bruno Mars", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("M83", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Calvin Harris", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Justin Bieber", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Robbie Williams", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Eric Prydz", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Linkin Park", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Lady Gaga", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Bon Jovi", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Rise Against", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("The Lumineers", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Jimi Hendrix", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Davig Guetta (Ft Akon)", now(), now(), 0);
INSERT INTO backend_artist (name, date_created, date_modified, is_deleted) VALUES ("Kanye West & Jay-Z", now(), now(), 0);

-- Create a bunch of music tracks with albums, artists and categories.
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Here Without You", (SELECT id from backend_album where name="Away From the Sun"), (SELECT id from backend_artist where name="3 Doors Down"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Kryptonite", (SELECT id from backend_album where name="The Better Life"), (SELECT id from backend_artist where name="3 Doors Down"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("My Life", (SELECT id from backend_album where name="Street King Immortal"), (SELECT id from backend_artist where name="50 cent"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Back in Black", (SELECT id from backend_album where name="Best of AC/DC"), (SELECT id from backend_artist where name="AC/DC"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Skyfall", (SELECT id from backend_album where name="21"), (SELECT id from backend_artist where name="Adele"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Angel", (SELECT id from backend_album where name="Angel Single"), (SELECT id from backend_artist where name="Akon"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ RnB"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Right Now (Na Na Na)", (SELECT id from backend_album where name="Freedom"), (SELECT id from backend_artist where name="Akon"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ RnB"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Smack That", (SELECT id from backend_album where name="Konvict"), (SELECT id from backend_artist where name="Akon ft Eminem"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ RnB"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Beautiful", (SELECT id from backend_album where name="Freedom"), (SELECT id from backend_artist where name="Akon, Colby O'Donis & Kardinal Offishal"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ RnB"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("City of Dreams", (SELECT id from backend_album where name="City of Dreams"), (SELECT id from backend_artist where name="Alesso & Dirty South"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Girl on Fire", (SELECT id from backend_album where name="Girl on Fire"), (SELECT id from backend_artist where name="Alicia Keys"), "none", (SELECT id from backend_musiccategory where name="R&B/ Soul"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Fluorescent Adolescent", (SELECT id from backend_album where name="Favourite Worst Nightmare"), (SELECT id from backend_artist where name="Arctic Monkeys"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Broken Tonight", (SELECT id from backend_album where name=""), (SELECT id from backend_artist where name="Armin Van Buuren"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Levels", (SELECT id from backend_album where name="Serious Things"), (SELECT id from backend_artist where name="Avicii"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Leave the World Behind", (SELECT id from backend_album where name="Axwell Presents Axtone Vol.1"), (SELECT id from backend_artist where name="Axwell, Ingrosso & Laidback Luke"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Love On Top", (SELECT id from backend_album where name="4"), (SELECT id from backend_artist where name="Beyonce"), "none", (SELECT id from backend_musiccategory where name="R&B/ Soul"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("All the Small Things", (SELECT id from backend_album where name="Enema of the State"), (SELECT id from backend_artist where name="Blink-182"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("It's my life", (SELECT id from backend_album where name="Bon Jovi: Greatest Hits"), (SELECT id from backend_artist where name="Bon Jovi"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Livin' on a Prayer", (SELECT id from backend_album where name="Cross Road"), (SELECT id from backend_artist where name="Bon Jovi"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("You Give Love a Bad Name", (SELECT id from backend_album where name="Cross Road"), (SELECT id from backend_artist where name="Bon Jovi"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("I Will Not Bow", (SELECT id from backend_album where name="Dear Agony"), (SELECT id from backend_artist where name="Breaking Benjamin"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Grenade", (SELECT id from backend_album where name="Doo-Wops & Hooligans"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("It Will Rain", (SELECT id from backend_album where name="The Twilight Sage: Breaking Dawn"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Just the Way You Are", (SELECT id from backend_album where name="Doo-Wops & Hooligans"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Locked Out Of Heaven", (SELECT id from backend_album where name="Unorthodox Jukebox"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Marry You", (SELECT id from backend_album where name="Doo-Wops & Hooligans"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Lazy Song", (SELECT id from backend_album where name="Doo-Wops & Hooligans"), (SELECT id from backend_artist where name="Bruno Mars"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Summer of 69", (SELECT id from backend_album where name="Anthology"), (SELECT id from backend_artist where name="Bryan Adams"), "none", (SELECT id from backend_musiccategory where name=""), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Drinking from the Bottle", (SELECT id from backend_album where name="18 Months"), (SELECT id from backend_artist where name="Calvin Harris"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Feel so Close", (SELECT id from backend_album where name="Feel So Close"), (SELECT id from backend_artist where name="Calvin Harris"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Let's Go (ft. Neyo)", (SELECT id from backend_album where name="18 Months"), (SELECT id from backend_artist where name="Calvin Harris"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Sweet Nothing", (SELECT id from backend_album where name="18 Months"), (SELECT id from backend_artist where name="Calvin Harris"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Call Me Maybe", (SELECT id from backend_album where name="Curiosity"), (SELECT id from backend_artist where name="Carly Rae Jepsen"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("A Thousand Years", (SELECT id from backend_album where name="The Twilight Saga: Breaking Dawn"), (SELECT id from backend_artist where name="Christina Perri"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Paradise", (SELECT id from backend_album where name="Mylo Xyloto"), (SELECT id from backend_artist where name="Coldplay"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Just One Last Time", (SELECT id from backend_album where name="Nothing but the Beat"), (SELECT id from backend_artist where name="David Guetta"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Without You", (SELECT id from backend_album where name="Nothing But The Beat"), (SELECT id from backend_artist where name="David Guetta"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Titanium (Feat. Sia)", (SELECT id from backend_album where name="Titanium"), (SELECT id from backend_artist where name="David Guetta & Sia"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Sexy Chic", (SELECT id from backend_album where name="One More Love"), (SELECT id from backend_artist where name="Davig Guetta (Ft Akon)"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Headlines", (SELECT id from backend_album where name="Take Care"), (SELECT id from backend_artist where name="Drake"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Take Care", (SELECT id from backend_album where name="Take Care"), (SELECT id from backend_artist where name="Drake"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Motto (ft Lil Wayne)", (SELECT id from backend_album where name="Take Care"), (SELECT id from backend_artist where name="Drake"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Real Her (ft Andre 300 & Lil Wayne)", (SELECT id from backend_album where name="Take Care"), (SELECT id from backend_artist where name="Drake"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Lights", (SELECT id from backend_album where name="Lights"), (SELECT id from backend_artist where name="Ellie Goulding"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Lose Yourself", (SELECT id from backend_album where name="Lose Yourself"), (SELECT id from backend_artist where name="Eminem"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Mockingbird", (SELECT id from backend_album where name="Curtain Call: The Hits"), (SELECT id from backend_artist where name="Eminem"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Real Slim Shady", (SELECT id from backend_album where name="Curtain Call: The Hits"), (SELECT id from backend_artist where name="Eminem"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Til I Collapse", (SELECT id from backend_album where name="The Eminem Show"), (SELECT id from backend_artist where name="Eminem"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Call On Me", (SELECT id from backend_album where name="Call On Me"), (SELECT id from backend_artist where name="Eric Prydz"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Pjanoo (Club Mix)", (SELECT id from backend_album where name="Pjanoo"), (SELECT id from backend_artist where name="Eric Prydz"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Good Feeling", (SELECT id from backend_album where name="Wild Ones"), (SELECT id from backend_artist where name="Flo Rida"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Let It Roll", (SELECT id from backend_album where name="Wild Ones"), (SELECT id from backend_artist where name="Flo Rida"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Whistle", (SELECT id from backend_album where name="Wild Ones"), (SELECT id from backend_artist where name="Flo Rida"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Best Of U", (SELECT id from backend_album where name="Foo Fighters"), (SELECT id from backend_artist where name="Foo Fighters"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Pumped Up Kicks", (SELECT id from backend_album where name="Torches"), (SELECT id from backend_artist where name="Foster The People"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("We are young", (SELECT id from backend_album where name="We Are Young"), (SELECT id from backend_artist where name="fun."), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Somebody That I Used To Know", (SELECT id from backend_album where name="Making Mirrors"), (SELECT id from backend_artist where name="Gotye"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("When I Come Around", (SELECT id from backend_album where name="Dookie"), (SELECT id from backend_artist where name="Green Day"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Paradise City", (SELECT id from backend_album where name="Appetite for Destruction"), (SELECT id from backend_artist where name="Guns N' Roses"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Stereo Hearts", (SELECT id from backend_album where name="GoodMusicAllDay.com Presents The Best Of June 5 - 10, 2011"), (SELECT id from backend_artist where name="Gym Class Heroes [Ft. Adam Levine]"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("It's Time", (SELECT id from backend_album where name="It's Time"), (SELECT id from backend_artist where name="Imagine Dragons"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("All Along the Watchtower", (SELECT id from backend_album where name="The Ultimate Experience"), (SELECT id from backend_artist where name="Jimi Hendrix"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Beauty and a Beat", (SELECT id from backend_album where name="Believe"), (SELECT id from backend_artist where name="Justin Bieber"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Suit and Tie", (SELECT id from backend_album where name="The 20/20 Experience"), (SELECT id from backend_artist where name="Justin Timberlake"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Clique", (SELECT id from backend_album where name="Clique"), (SELECT id from backend_artist where name="Kanye West"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Niggas In Paris", (SELECT id from backend_album where name="Watch the Throne"), (SELECT id from backend_artist where name="Kanye West & Jay-Z"), "none", (SELECT id from backend_musiccategory where name="HIP Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The One That Got Away", (SELECT id from backend_album where name="Teenage Dream"), (SELECT id from backend_artist where name="Katy Perry"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("C'mon", (SELECT id from backend_album where name="Warrior"), (SELECT id from backend_artist where name="Ke$ha"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Die Young", (SELECT id from backend_album where name="Warrior"), (SELECT id from backend_artist where name="Ke$ha"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Pursuit Of Happiness", (SELECT id from backend_album where name="Man on the Moon: The End of Day"), (SELECT id from backend_artist where name="Kid Cudi"), "none", (SELECT id from backend_musiccategory where name="HIP Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Marry The Night", (SELECT id from backend_album where name="Born This Way"), (SELECT id from backend_artist where name="Lady Gaga"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Stairway to Heaven", (SELECT id from backend_album where name="[Led Zeppelin IV]"), (SELECT id from backend_artist where name="Led Zeppelin"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Crawling", (SELECT id from backend_album where name="Hybrid Theory"), (SELECT id from backend_artist where name="Linkin Park"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Faint", (SELECT id from backend_album where name="Meteora"), (SELECT id from backend_artist where name="Linkin Park"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("In the End", (SELECT id from backend_album where name="Hybrid Theory"), (SELECT id from backend_artist where name="Linkin Park"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Numb", (SELECT id from backend_album where name="Live in Texas"), (SELECT id from backend_artist where name="Linkin Park"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Somewhere I Belong", (SELECT id from backend_album where name="Meteora"), (SELECT id from backend_artist where name="Linkin Park"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Party Rock Anthem", (SELECT id from backend_album where name="Party Rock Anthem"), (SELECT id from backend_artist where name="LMFAO"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Sexy and I Know It", (SELECT id from backend_album where name="Sorry for Party Rocking"), (SELECT id from backend_artist where name="LMFAO"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Midnight City", (SELECT id from backend_album where name="Hurry Up, We\'e2\'80\'99re Dreaming"), (SELECT id from backend_artist where name="M83"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Thrift Shop", (SELECT id from backend_album where name="The Heist"), (SELECT id from backend_artist where name="Macklemore"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Daylight", (SELECT id from backend_album where name="Overexposed"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Moves Like Jagger", (SELECT id from backend_album where name="Hands All Over"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("One More Night", (SELECT id from backend_album where name="Overexposed"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Payphone", (SELECT id from backend_album where name="Overexposed"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("She Will Be Loved", (SELECT id from backend_album where name="Songs About Jane"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("This Love", (SELECT id from backend_album where name="This Love"), (SELECT id from backend_artist where name="Maroon 5"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Enter Sandman", (SELECT id from backend_album where name="No Leaf Clover"), (SELECT id from backend_artist where name="Metallica"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Unforgiven II", (SELECT id from backend_album where name="Reload"), (SELECT id from backend_artist where name="Metallica"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Bad Girls", (SELECT id from backend_album where name="Matangi"), (SELECT id from backend_artist where name="M.I.A"), "none", (SELECT id from backend_musiccategory where name="Electronic"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Electric Feel (Album Version)", (SELECT id from backend_album where name="Oracular Spectacular"), (SELECT id from backend_artist where name="MGMT"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Kids (Album Version)", (SELECT id from backend_album where name="Oracular Spectacular"), (SELECT id from backend_artist where name="MGMT"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Starlight", (SELECT id from backend_album where name="Black Holes and Revelations"), (SELECT id from backend_artist where name="Muse"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Uprising (Album Version)", (SELECT id from backend_album where name="Uprising"), (SELECT id from backend_artist where name="Muse"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Just a Dream", (SELECT id from backend_album where name="Just a Dream"), (SELECT id from backend_artist where name="Nelly"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Far Away", (SELECT id from backend_album where name="All The Right Reasons"), (SELECT id from backend_artist where name="Nickelback"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Starships", (SELECT id from backend_album where name="Pink Friday"), (SELECT id from backend_artist where name="Nicki Minaj"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Super Bass", (SELECT id from backend_album where name="Pink Friday"), (SELECT id from backend_artist where name="Nicki Minaj"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("In Bloom", (SELECT id from backend_album where name="Nirvana"), (SELECT id from backend_artist where name="Nirvana"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Smells Like Teen Spirit", (SELECT id from backend_album where name="Nirvana"), (SELECT id from backend_artist where name="Nirvana"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Wonderwall", (SELECT id from backend_album where name="(What's The Story) Morning Glory?"), (SELECT id from backend_artist where name="Oasis/oasis"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Little Talks", (SELECT id from backend_album where name="My Head Is an Animal"), (SELECT id from backend_artist where name="Of Monsters and Men"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Kiss You", (SELECT id from backend_album where name="Take Me Home"), (SELECT id from backend_artist where name="One direction"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("What Makes You Beautiful", (SELECT id from backend_album where name="Up All Night"), (SELECT id from backend_artist where name="One direction"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Good Life", (SELECT id from backend_album where name="Waking Up"), (SELECT id from backend_artist where name="OneRepublic"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Just Breathe", (SELECT id from backend_album where name="Backspacer"), (SELECT id from backend_artist where name="Pearl Jam"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Island", (SELECT id from backend_album where name="Immersion"), (SELECT id from backend_artist where name="Pendulum"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Blow Me", (SELECT id from backend_album where name="The Truth About Love"), (SELECT id from backend_artist where name="Pink"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Try", (SELECT id from backend_album where name="The Truth About Love"), (SELECT id from backend_artist where name="Pink"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Don’t Stop the Party", (SELECT id from backend_album where name="Global Warming"), (SELECT id from backend_artist where name="Pitbull"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Gangnam Style", (SELECT id from backend_album where name="PSY 6"), (SELECT id from backend_artist where name="Psy"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Don't Stop Me Now", (SELECT id from backend_album where name="Greatest Hits"), (SELECT id from backend_artist where name="Queen"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("By the Way", (SELECT id from backend_album where name="By the Way"), (SELECT id from backend_artist where name="Red Hot Chili Peppers"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Scar Tissue (Album Version)", (SELECT id from backend_album where name="Scar Tissue"), (SELECT id from backend_artist where name="Red Hot Chili Peppers"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("The Zephyr Song", (SELECT id from backend_album where name="By the Way"), (SELECT id from backend_artist where name="Red Hot Chili Peppers"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Diamonds", (SELECT id from backend_album where name="Unapologetic"), (SELECT id from backend_artist where name="Rihanna"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Rude Boy", (SELECT id from backend_album where name="Rated R"), (SELECT id from backend_artist where name="Rihanna"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("We Found Love", (SELECT id from backend_album where name="Talk That Talk"), (SELECT id from backend_artist where name="Rihanna"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Where Have You Been", (SELECT id from backend_album where name="Talk That Talk"), (SELECT id from backend_artist where name="Rihanna"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Prayer of the Refugee", (SELECT id from backend_album where name="The Sufferer & the Witness"), (SELECT id from backend_artist where name="Rise Against"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Satellite", (SELECT id from backend_album where name="Endgame"), (SELECT id from backend_artist where name="Rise Against"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Savior", (SELECT id from backend_album where name="Appeal to Reason"), (SELECT id from backend_artist where name="Rise Against"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Candy", (SELECT id from backend_album where name="Take the Crown"), (SELECT id from backend_artist where name="Robbie Williams"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Bangarang", (SELECT id from backend_album where name="ThisSongIsSick.com"), (SELECT id from backend_artist where name="Skrillex"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Cinema", (SELECT id from backend_album where name="Scary Monsters and Nice Sprites"), (SELECT id from backend_artist where name="Skrillex"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Kill EVERYBODY", (SELECT id from backend_album where name="Scary Monsters and Nice Sprites"), (SELECT id from backend_artist where name="Skrillex"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Scary Monsters and Nice Spirits", (SELECT id from backend_album where name="Scary Monsters and Nice Sprites"), (SELECT id from backend_artist where name="Skrillex"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Scary Monsters and Nice Sprites", (SELECT id from backend_album where name="Scary Monsters and Nice Sprites"), (SELECT id from backend_artist where name="Skrillex"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Santeria", (SELECT id from backend_album where name="Sublime"), (SELECT id from backend_artist where name="Sublime"), "none", (SELECT id from backend_musiccategory where name=""), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Don't You Worry Child", (SELECT id from backend_album where name="Until Now"), (SELECT id from backend_artist where name="Swedish House Mafia"), "none", (SELECT id from backend_musiccategory where name="Dance"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("I Knew You Were Trouble", (SELECT id from backend_album where name="Red"), (SELECT id from backend_artist where name="Taylor Swift"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("We Are Never Getting Back Together", (SELECT id from backend_album where name="Red"), (SELECT id from backend_artist where name="Taylor Swift"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Gold on the Ceiling", (SELECT id from backend_album where name="El Camino"), (SELECT id from backend_artist where name="The Black Keys"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Lonely Boy", (SELECT id from backend_album where name="El Camino"), (SELECT id from backend_artist where name="The Black Keys"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Ho Hey", (SELECT id from backend_album where name="Daytrotter Studio  10/11/2011"), (SELECT id from backend_artist where name="The Lumineers"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Every Little Thing She Does Is Magic", (SELECT id from backend_album where name="The Police"), (SELECT id from backend_artist where name="The Police"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Last Night", (SELECT id from backend_album where name="Is This It"), (SELECT id from backend_artist where name="The Strokes"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Wicked Games", (SELECT id from backend_album where name="Trilogy"), (SELECT id from backend_artist where name="The Weeknd"), "none", (SELECT id from backend_musiccategory where name="RnB/Soul"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Drive By", (SELECT id from backend_album where name="Drive By"), (SELECT id from backend_artist where name="Train"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Do My Dance", (SELECT id from backend_album where name="Well Done 3"), (SELECT id from backend_artist where name="Tyga"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Faded (ft. Lil wayne)", (SELECT id from backend_album where name="Faded"), (SELECT id from backend_artist where name="Tyga"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Rack City", (SELECT id from backend_album where name="Rack City- Single"), (SELECT id from backend_artist where name="Tyga"), "none", (SELECT id from backend_musiccategory where name="Hip Hop/ Rap"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Beatiful Day", (SELECT id from backend_album where name="U2 18 Greatest Hits"), (SELECT id from backend_artist where name="U2"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("One", (SELECT id from backend_album where name="Greatest Hits"), (SELECT id from backend_artist where name="U2"), "none", (SELECT id from backend_musiccategory where name="Rock"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("DJ Got Us Falling In Love Again", (SELECT id from backend_album where name="DJ Got Us Falling In Love Again"), (SELECT id from backend_artist where name="Usher"), "none", (SELECT id from backend_musiccategory where name="RnB/Soul"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Island in the Sun", (SELECT id from backend_album where name="Weezer (Green Album)"), (SELECT id from backend_artist where name="Weezer"), "none", (SELECT id from backend_musiccategory where name="Alternative"), now(), now());
INSERT INTO backend_musictrack (name, album_id, artist_id, track_URL, category_id, date_created, date_modified) VALUES ("Scream and Shout", (SELECT id from backend_album where name="willpower"), (SELECT id from backend_artist where name="will.i.am"), "none", (SELECT id from backend_musiccategory where name="Pop"), now(), now());

-- Update with album art
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/3_doors_down_away_from_the_sun' WHERE name='Away From the Sun';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/3_Doors_Down_The_Better_Life-Frontal' WHERE name='The Better Life';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/50_cent_my_life.jpg' WHERE name='Street King Immortal';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/ACDC_back_in_black' WHERE name='Best of AC/DC';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/adele_21.jpg' WHERE name='21';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/akon_angel' WHERE name='Angel Single';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/akon_freedom' WHERE name='Freedom';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/akon_konvict.jpg' WHERE name='Konvict';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/akon_freedom' WHERE name='Freedom';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/alesso_city_of_dreams' WHERE name='City of Dreams';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/alicia_keys_girl_on_fire.jpg' WHERE name='Girl on Fire';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/arctic_monkey_favorite_worst_nightmare' WHERE name='Favourite Worst Nightmare';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/Armin_van_buuren_broken_tonight' WHERE name='';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/avicii_levels.jpg' WHERE name='Serious Things';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/Axwell_axtone_no1' WHERE name='Axwell Presents Axtone Vol.1';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/beyonce_4.jpg' WHERE name='4';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/blink_182_enema_of_the_state' WHERE name='Enema of the State';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bon_jovi_greatest_hits' WHERE name='Bon Jovi: Greatest Hits';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/Bon_Jovi-Cross_Road' WHERE name='Cross Road';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/Bon_Jovi-Cross_Road' WHERE name='Cross Road';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/breaking_benjamin_dear_agony' WHERE name='Dear Agony';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_mars_doo_wops_and_hooligans' WHERE name='Doo-Wops & Hooligans';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_marks_breaking_dawn.jpg' WHERE name='The Twilight Sage: Breaking Dawn';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_mars_doo_wops_and_hooligans' WHERE name='Doo-Wops & Hooligans';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_mars_unorthodox_jukebox.jpg' WHERE name='Unorthodox Jukebox';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_mars_doo_wops_and_hooligans' WHERE name='Doo-Wops & Hooligans';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bruno_mars_doo_wops_and_hooligans' WHERE name='Doo-Wops & Hooligans';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/bryan_adams_anthology' WHERE name='Anthology';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/calvin_harris_18_months.jpg' WHERE name='18 Months';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/calvin_harris-feel_so_close' WHERE name='Feel So Close';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/calvin_harris_18_months.jpg' WHERE name='18 Months';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/calvin_harris_18_months.jpg' WHERE name='18 Months';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/carly_rae_jepsen_curiosity.jpg' WHERE name='Curiosity';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/coldplay_mylo_xyloto.jpg' WHERE name='Mylo Xyloto';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/david_guetta_nothing_but_the_beat.jpg' WHERE name='Nothing but the Beat';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/david_guetta_nothing_but_the_beat.jpg' WHERE name='Nothing But The Beat';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/david_guetta_one_more_love.jpg' WHERE name='One More Love';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/drake_take_care.jpg' WHERE name='Take Care';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/flo_rida_wild_ones.jpg' WHERE name='Wild Ones';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/flo_rida_wild_ones.jpg' WHERE name='Wild Ones';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/flo_rida_wild_ones.jpg' WHERE name='Wild Ones';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/justin_bieber_believe' WHERE name='Believe';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/justin_timberlake_the_20_20_experience.jpg' WHERE name='The 20/20 Experience';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/kanye_clique.jpg' WHERE name='Clique';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/katy_perry_teenage_dream.jpg' WHERE name='Teenage Dream';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/kesha_warrior' WHERE name='Warrior';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/kesha_warrior' WHERE name='Warrior';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/lady_gaga_born_this_way.jpg' WHERE name='Born This Way';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/maroon_5_daylight.jpg' WHERE name='Overexposed';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/maroon_5_hands_all_over.jpg' WHERE name='Hands All Over';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/maroon_5_overexposed.jpg' WHERE name='Overexposed';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/maroon_5_overexposed.jpg' WHERE name='Overexposed';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/nickelback_all_the_right_reasons.jpg' WHERE name='All The Right Reasons';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/one_direction_take_me_home.jpg' WHERE name='Take Me Home';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/one_direction_up_all_night.jpg' WHERE name='Up All Night';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/pendulum_immersion.jpg' WHERE name='Immersion';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/pink_truth_about_love' WHERE name='The Truth About Love';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/pink_truth_about_love' WHERE name='The Truth About Love';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/pitbull_global_warming.jpg' WHERE name='Global Warming';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/psy_psy6.jpg' WHERE name='PSY 6';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/rihanna_apologetic.jpg' WHERE name='Unapologetic';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/rihanna_talk_that_talk.jpg' WHERE name='Talk That Talk';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/robbie_williams_take_the_crown' WHERE name='Take the Crown';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/skrillex_scary_monsters.jpg' WHERE name='Scary Monsters and Nice Sprites';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/swedish_house_mafia_until_now.jpg' WHERE name='Until Now';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/taylor_swift_red.jpg' WHERE name='Red';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/taylor_swift_red.jpg' WHERE name='Red';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/the_weekend_trilogy.jpg' WHERE name='Trilogy';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/tyga_well_done_3.jpg' WHERE name='Well Done 3';
UPDATE backend_album SET image_URL='http://api.soundit.ca/static/album/william_scream_and_shout.jpg' WHERE name='willpower';

-- Create playlist items, all linked to that one playlist. This will have to be done through the venue app.
INSERT INTO backend_playlistitem (playlist_id, music_track_id, votes, rank_played, current_ranking, date_created, date_modified, item_state) VALUES (1, 3, 0, 0, 0, now(), now(), 1);
